"""Indonesian stopword list and filtering rules for Crab News."""

from typing import Set

# Curated list of Indonesian stopwords and common web boilerplate tokens
INDONESIAN_STOPWORDS: Set[str] = {
    # Pronouns & Prepositions
    "ada", "adalah", "adanya", "adapun", "agak", "agar", "akan", "akankah", "akhir", "akhiri", "akhirnya",
    "aku", "akulah", "amat", "amatlah", "anda", "andalah", "antar", "antara", "antaranya", "apa",
    "apaan", "apabila", "apakah", "apalagi", "apalah", "artinya", "asal", "asalkan", "atas", "atau",
    "ataukah", "ataupun", "awal", "awalnya", "bagai", "bagaikan", "bagaimana", "bagaimanakah", "bagaimanapun",
    "bagi", "bahkan", "bahwa", "bahwasanya", "baik", "bakal", "banyak", "banyaknya", "bapak", "baru",
    "bawah", "beberapa", "begini", "beginian", "beginikah", "beginilah", "begitu", "begitukah", "begitulah",
    "begitupun", "bekerja", "belakang", "belakangan", "belum", "belumlah", "benar", "benarkah", "benarlah",
    "berada", "berakhir", "berapa", "berapakah", "berapalah", "berapapun", "berarti", "berawal", "berbagai",
    "beri", "berikan", "berikut", "berikutnya", "berjumlah", "berkenaan", "berlainan", "berlalu", "berlangsung",
    "bermula", "bersama", "bersiap", "bertanya", "berturut", "bertutur", "berujar", "berupa", "besar",
    "betul", "betulkah", "biasa", "biasanya", "bila", "bilakah", "bisa", "bisakah", "boleh", "bolehkah",
    "bukan", "bukankah", "bukanlah", "bukannya", "cukup", "cukupkah", "cukuplah", "cuma", "dahulu",
    "dalam", "dan", "dapat", "dari", "daripada", "dekat", "demi", "demikian", "demikianlah", "dengan",
    "depan", "di", "dia", "dialah", "diantara", "diantaranya", "diberi", "diberikan", "diberikannya",
    "dibuat", "dibuatnya", "didapat", "didatangkan", "digunakan", "diibaratkan", "diingat", "diingatkan",
    "diinginkan", "dijawab", "dijelaskan", "dijelaskannya", "dikarenakan", "dikatakan", "dikatakannya",
    "dikerjakan", "diketahui", "diketahuinya", "dikira", "dilakukan", "dilalui", "dilihat", "dimaksud",
    "dimaksudkan", "dimaksudkannya", "dimaksudnya", "diminta", "dimintai", "dimisalkan", "dimulai",
    "dimulailah", "dimulainya", "dimungkinkan", "dini", "dipastikan", "diperbuat", "diperbuatnya",
    "dipergunakan", "diperkirakan", "diperlihatkan", "diperlukan", "diperlukannya", "dipersoalkan",
    "dipertanyakan", "dipunyai", "diri", "dirinya", "disampaikan", "disebut", "disebutkan", "disebutkannya",
    "disini", "disinilah", "ditambahkan", "ditandaskan", "ditanya", "ditanyai", "ditanyakan", "ditegaskan",
    "ditemukan", "ditentukan", "ditentukannya", "ditunjuk", "ditunjuki", "ditunjukkan", "ditunjukkannya",
    "ditunjuknya", "dituturkan", "dituturkannya", "diucapkan", "diucapkannya", "diungkapkan", "dong",
    "dulu", "empat", "enggak", "enggaknya", "entah", "entahlah", "guna", "gunakan", "hal", "hampir",
    "hanya", "hanyalah", "hari", "harus", "haruslah", "harusnya", "hendak", "hendaklah", "hendaknya",
    "hingga", "ia", "ialah", "ibarat", "ibaratkan", "ibaratnya", "ibu", "ikut", "ingat", "ingin",
    "inginkah", "inginkan", "ini", "inikah", "inilah", "itu", "itukah", "itulah", "jadi", "jadilah",
    "jadinya", "jangan", "jangankan", "janganlah", "jauh", "jawab", "jawaban", "jawabnya", "jelas",
    "jelaskan", "jelaslah", "jelasnya", "jika", "jikalau", "juga", "jumlah", "jumlahnya", "justru",
    "kala", "kalau", "kalaulah", "kalaupun", "kalian", "kami", "kamilah", "kamu", "kamulah", "kan",
    "kapan", "kapankah", "kapanpun", "karena", "karenanya", "kasus", "kata", "katakan", "katakanlah",
    "katanya", "ke", "keadaan", "kebetulan", "kecil", "kedua", "keduanya", "keinginan", "kelenjar",
    "kelihatan", "kelihatannya", "kelima", "keluar", "kembali", "kemudian", "kemungkinan", "kemungkinannya",
    "kenapa", "kepada", "kepadanya", "kesampaian", "keseluruhan", "keseluruhannya", "keterlaluan",
    "ketika", "khususnya", "kini", "kinilah", "kira", "kiranya", "kita", "kitalah", "kurang", "lagi",
    "lagian", "lah", "lain", "lainnya", "lalu", "lama", "lamanya", "lanjut", "lanjutnya", "lebih",
    "lewat", "lima", "luar", "macam", "maka", "makanya", "makin", "malah", "malahan", "mampu",
    "mampukah", "mana", "manakala", "manalagi", "masa", "masalah", "masalahnya", "masih", "masihkah",
    "masing", "mau", "maupun", "melainkan", "melakukan", "melalui", "melihat", "melihatnya", "memang",
    "memastikan", "memberi", "memberikan", "memberikannya", "membuat", "memerlukan", "memihak", "meminta",
    "memintakan", "memisalkan", "memperbuat", "mempergunakan", "memperkirakan", "memperlihatkan",
    "mempersiapkan", "mempersoalkan", "mempertanyakan", "mempunyai", "memulai", "memungkinkan", "menaiki",
    "menandaskan", "menanti", "menantikan", "menanya", "menanyai", "menanyakan", "mendapat", "mendapatkan",
    "mendatang", "mendatangi", "mendatangkan", "menegaskan", "mengakhiri", "mengapa", "mengatakan",
    "mengatakannya", "mengenai", "mengerjakan", "mengetahui", "menggunakan", "menghendaki", "mengibaratkan",
    "mengibaratkannya", "mengingat", "mengingatkan", "menginginkan", "mengira", "mengucapkan", "mengucapkannya",
    "mengungkapkan", "menjadi", "menjawab", "menjelaskan", "menuju", "menunjuk", "menunjuki", "menunjukkan",
    "menunjuknya", "menurut", "menurutnya", "menuturkan", "menuturkannya", "menyampaikan", "menyangkut",
    "menyatakan", "menyebutkan", "menyeluruh", "menyiapkan", "merasa", "mereka", "merekalah", "merupakan",
    "meski", "meskipun", "meyakini", "meyakinkan", "minta", "mirip", "misal", "misalkan", "misalnya",
    "mula", "mulai", "mulailah", "mulanya", "mungkin", "mungkinkah", "nah", "naik", "namun", "nanti",
    "nantinya", "nyaris", "nyatanya", "olah", "oleh", "olehnya", "pada", "padahal", "padanya", "pak",
    "paling", "panjang", "pantas", "para", "pasti", "pastilah", "penting", "pentingnya", "per", "percuma",
    "perlu", "perlukah", "perlunya", "pernah", "persoalan", "pertama", "pertamanya", "pertanyaan",
    "pertanyakan", "pihak", "pihaknya", "pula", "pulang", "pun", "punya", "rasa", "rasanya", "rata",
    "rupanya", "saat", "saatnya", "saja", "sajalah", "saling", "sama", "samakah", "sambil", "sampai",
    "sampaikan", "sana", "sangat", "sangatlah", "satu", "saya", "sayalah", "se", "sebab", "sebabnya",
    "sebagai", "sebagaimana", "sebagainya", "sebagian", "sebaik", "sebaiknya", "sebaliknya", "sebanyak",
    "sebegini", "sebegitu", "sebelum", "sebelumnya", "sebenarnya", "seberapa", "sebesar", "sebetulnya",
    "sebisanya", "sebuah", "sebut", "sebutlah", "sebutnya", "secara", "secukupnya", "sedang", "sedangkan",
    "sedemikian", "sedikit", "sedikitnya", "seenaknya", "segala", "segalanya", "segera", "seharusnya",
    "sehingga", "seingat", "sejak", "sejauh", "sejenak", "sejumlah", "sekadar", "sekadarnya", "sekali",
    "sekalian", "sekaligus", "sekalipun", "sekarang", "sekaranglah", "sekecil", "seketika", "sekiranya",
    "sekitar", "sekitarnya", "sekurang", "sekurangnya", "sela", "selain", "selalu", "selama", "selamanya",
    "selanjutnya", "seluruh", "seluruhnya", "semacam", "semakin", "semampu", "semampunya", "semasa",
    "semasih", "semata", "sematanya", "semaunya", "sementara", "semisal", "semisalnya", "sempat",
    "semua", "semuanya", "semula", "sendiri", "sendirian", "sendirinya", "seolah", "seorang", "sepanjang",
    "sepantasnya", "sepantasnyalah", "seperlunya", "seperti", "sepertinya", "sepihak", "sering", "seringnya",
    "serta", "serupa", "sesaat", "sesama", "sesampai", "sesegera", "sesekali", "seseorang", "sesuatu",
    "sesuatunya", "sesudah", "sesudahnya", "setelah", "setempat", "setengah", "seterusnya", "setiap",
    "setiba", "setibanya", "setidak", "setidakknya", "setidaknya", "setinggi", "seusai", "sewaktu",
    "siap", "siapa", "siapakah", "siapapun", "sini", "sinilah", "soal", "soalnya", "suatu", "sudah",
    "sudahkah", "sudahlah", "supaya", "tadi", "tadinya", "tahu", "tak", "tambah", "tambahnya", "tampak",
    "tampaknya", "tanpa", "tanya", "tanyakan", "tanyanya", "tapi", "tegas", "tegasnya", "telah",
    "tempat", "tengah", "tentang", "tentu", "tentulah", "tentunya", "tepat", "terakhir", "terasa",
    "terbanyak", "terdahulu", "terdapat", "terdiri", "terhadap", "terhadapnya", "terhitung", "terikut",
    "terjadi", "terjadilah", "terjadinya", "terkira", "terlalu", "terlebih", "terlihat", "termasuk",
    "ternyata", "tersampaikan", "tersebut", "tersebutlah", "tertentu", "tertuju", "terus", "terusan",
    "tetap", "tetapi", "tiap", "tiba", "tidak", "tidakkah", "tidaklah", "tidaknya", "tiga", "toh",
    "tunjuk", "turut", "tutur", "tuturnya", "ucap", "ucapnya", "ujar", "ujarnya", "umum", "umumnya",
    "ungkap", "ungkapnya", "untuk", "usah", "usai", "waduh", "wah", "wahai", "waktu", "waktunya",
    "walau", "walaupun", "wong", "yaitu", "yakin", "yakni", "yang",
    
    # Common News & Web noise
    "baca", "klik", "halaman", "foto", "sumber", "detikcom", "kompascom", "cnn", "antara", "tempo",
    "tag", "terkait", "redaksi", "simak", "editor", "penulis", "reporter", "berita", "indonesia", "jakarta",
}


def is_stopword(word: str) -> bool:
    """Checks if a given lowercased word is an Indonesian stopword or noise."""
    return word.lower() in INDONESIAN_STOPWORDS
